// <auto-generated />
using System;
using BackendHamster;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendHamster.Migrations
{
    [DbContext(typeof(DbContextHamster))]
    [Migration("20210410093118_LazyLoading")]
    partial class LazyLoading
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendHamster.AktivityLogg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("aktiv")
                        .HasColumnType("int");

                    b.Property<int?>("hamsterLoggID")
                        .HasColumnType("int");

                    b.Property<DateTime>("timeLogg")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("hamsterLoggID");

                    b.ToTable("logg");
                });

            modelBuilder.Entity("BackendHamster.Cage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cageNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("cages");
                });

            modelBuilder.Entity("BackendHamster.Hamster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("inCheck")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("senastMotioneradTid")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("hamsters");
                });

            modelBuilder.Entity("BackendHamster.Motionsyta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("motionTid")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("motionsyta");
                });

            modelBuilder.Entity("BackendHamster.Object.Aktivities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("aktiviteter");
                });

            modelBuilder.Entity("BackendHamster.Object.CageBuddies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("cageHamsterID")
                        .HasColumnType("int");

                    b.Property<int?>("filledCageID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("cageHamsterID");

                    b.HasIndex("filledCageID");

                    b.ToTable("cageBuddies");
                });

            modelBuilder.Entity("BackendHamster.Object.motionBuddies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("activeHamsterID")
                        .HasColumnType("int");

                    b.Property<int?>("motionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("activeHamsterID");

                    b.HasIndex("motionID");

                    b.ToTable("motionBuddies");
                });

            modelBuilder.Entity("BackendHamster.AktivityLogg", b =>
                {
                    b.HasOne("BackendHamster.Hamster", "hamsterLogg")
                        .WithMany()
                        .HasForeignKey("hamsterLoggID");

                    b.Navigation("hamsterLogg");
                });

            modelBuilder.Entity("BackendHamster.Object.CageBuddies", b =>
                {
                    b.HasOne("BackendHamster.Hamster", "cageHamster")
                        .WithMany()
                        .HasForeignKey("cageHamsterID");

                    b.HasOne("BackendHamster.Cage", "filledCage")
                        .WithMany()
                        .HasForeignKey("filledCageID");

                    b.Navigation("cageHamster");

                    b.Navigation("filledCage");
                });

            modelBuilder.Entity("BackendHamster.Object.motionBuddies", b =>
                {
                    b.HasOne("BackendHamster.Hamster", "activeHamster")
                        .WithMany()
                        .HasForeignKey("activeHamsterID");

                    b.HasOne("BackendHamster.Motionsyta", "motion")
                        .WithMany()
                        .HasForeignKey("motionID");

                    b.Navigation("activeHamster");

                    b.Navigation("motion");
                });
#pragma warning restore 612, 618
        }
    }
}
