// <auto-generated />
using System;
using BackendHamster;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendHamster.Migrations
{
    [DbContext(typeof(DbContextHamster))]
    [Migration("20210409171340_addedSixHamstersToMotion")]
    partial class addedSixHamstersToMotion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendHamster.AktivityLogg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("aktiv")
                        .HasColumnType("int");

                    b.Property<int?>("hamsterLoggID")
                        .HasColumnType("int");

                    b.Property<DateTime>("timeLogg")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("hamsterLoggID");

                    b.ToTable("logg");
                });

            modelBuilder.Entity("BackendHamster.Cage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cageNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("cages");
                });

            modelBuilder.Entity("BackendHamster.Hamster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("inCheck")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("senastMotioneradTid")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("hamsters");
                });

            modelBuilder.Entity("BackendHamster.Motionsyta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("aktivHamsterFiveID")
                        .HasColumnType("int");

                    b.Property<int?>("aktivHamsterFourID")
                        .HasColumnType("int");

                    b.Property<int?>("aktivHamsterOneID")
                        .HasColumnType("int");

                    b.Property<int?>("aktivHamsterSixID")
                        .HasColumnType("int");

                    b.Property<int?>("aktivHamsterThreeID")
                        .HasColumnType("int");

                    b.Property<int?>("aktivHamsterTwoID")
                        .HasColumnType("int");

                    b.Property<int>("motionTid")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("aktivHamsterFiveID");

                    b.HasIndex("aktivHamsterFourID");

                    b.HasIndex("aktivHamsterOneID");

                    b.HasIndex("aktivHamsterSixID");

                    b.HasIndex("aktivHamsterThreeID");

                    b.HasIndex("aktivHamsterTwoID");

                    b.ToTable("motionsyta");
                });

            modelBuilder.Entity("BackendHamster.Object.Aktivities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("aktiviteter");
                });

            modelBuilder.Entity("BackendHamster.Object.CageBuddies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("cageHamsterID")
                        .HasColumnType("int");

                    b.Property<int?>("filledCageID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("cageHamsterID");

                    b.HasIndex("filledCageID");

                    b.ToTable("cageBuddies");
                });

            modelBuilder.Entity("BackendHamster.AktivityLogg", b =>
                {
                    b.HasOne("BackendHamster.Hamster", "hamsterLogg")
                        .WithMany()
                        .HasForeignKey("hamsterLoggID");

                    b.Navigation("hamsterLogg");
                });

            modelBuilder.Entity("BackendHamster.Motionsyta", b =>
                {
                    b.HasOne("BackendHamster.Hamster", "aktivHamsterFive")
                        .WithMany()
                        .HasForeignKey("aktivHamsterFiveID");

                    b.HasOne("BackendHamster.Hamster", "aktivHamsterFour")
                        .WithMany()
                        .HasForeignKey("aktivHamsterFourID");

                    b.HasOne("BackendHamster.Hamster", "aktivHamsterOne")
                        .WithMany()
                        .HasForeignKey("aktivHamsterOneID");

                    b.HasOne("BackendHamster.Hamster", "aktivHamsterSix")
                        .WithMany()
                        .HasForeignKey("aktivHamsterSixID");

                    b.HasOne("BackendHamster.Hamster", "aktivHamsterThree")
                        .WithMany()
                        .HasForeignKey("aktivHamsterThreeID");

                    b.HasOne("BackendHamster.Hamster", "aktivHamsterTwo")
                        .WithMany()
                        .HasForeignKey("aktivHamsterTwoID");

                    b.Navigation("aktivHamsterFive");

                    b.Navigation("aktivHamsterFour");

                    b.Navigation("aktivHamsterOne");

                    b.Navigation("aktivHamsterSix");

                    b.Navigation("aktivHamsterThree");

                    b.Navigation("aktivHamsterTwo");
                });

            modelBuilder.Entity("BackendHamster.Object.CageBuddies", b =>
                {
                    b.HasOne("BackendHamster.Hamster", "cageHamster")
                        .WithMany()
                        .HasForeignKey("cageHamsterID");

                    b.HasOne("BackendHamster.Cage", "filledCage")
                        .WithMany()
                        .HasForeignKey("filledCageID");

                    b.Navigation("cageHamster");

                    b.Navigation("filledCage");
                });
#pragma warning restore 612, 618
        }
    }
}
